baseURL = "https://lassunsreden.ch/"
languageCode = "de-ch"
title = "Systemische Beratung & Therapie | Marie Lass"
disableKinds = ["taxonomy", "term"]

[params]
description = "Lass uns reden, Problem! Ich unterst√ºtze Sie bei einem konstruktiven Dialog, der den Abschied von Ihrem Problem erleichtert."